[project]
name = "tools-in-data-science-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
]
